# TODO: Find a way to merg namespace arg and the frame name params

# Pointcloud Cropping Inputs
crop_box:
  # Frame crop box is defined in
  input_frame: rs_camera_1_link #$(arg name_space)_link
  # Frame data is to be output in
  output_frame: rs_camera_1_color_optical_frame #$(arg name_space)_color_optical_frame

  min_x:  0.2
  max_x:  0.8
  min_y: -0.2
  max_y:  0.2
  min_z: -0.5
  max_z:  0.5
