# !! Currently not being used !!
# Pointcloud Cropping Inputs
crop:
  dim_input_frame: map
  data_output_frame: $(arg name_space)_color_optical_frame

  min_x: -0.5
  max_x:  2.1
  min_y: -1.0
  max_y: -0.5
  min_z:  0.7
  max_z:  1.4
