# TODO: Find a way to merg namespace arg and the frame name params

# Pointcloud Cropping Inputs
crop_box:
  # Frame crop box is defined in
  input_frame: map
  # Frame data is to be output in
  output_frame: camera_color_optical_frame #$(arg name_space)_color_optical_frame

  min_x: -0.5
  max_x:  2.1
  min_y: -1.0
  max_y: -0.5
  min_z:  0.7
  max_z:  1.4
